### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by botiapa** [DankBSD/wf-wallpaper#1]
I'm getting some errors while trying to get the plugin to compile. 
`gcc --version`: `gcc (GCC) 10.2.0`
`meson --version`: `0.57.1`
`ninja --version`: `1.10.2`

Here are the logs: [ix.io](http://ix.io/2Td5)

The commands I ran:
1. `git clone`
2. `meson setup builddir`
3. `meson compile`

I'm thinking this is a gcc version issue, but I'm not sure.

**Comment by unrelentingtech** [comment]
Shouldn't really be anything to do with gcc.

> error: ‘workspace_grid_changed_signal’ is not a member of ‘wf’; did you mean ‘workspace_changed_signal’?

Your wayfire is too old, you need at least https://github.com/WayfireWM/wayfire/commit/a4ff53d8715ae180c2531d4e25434487a56609d4

> error: invalid conversion from ‘int’ to ‘idtype_t’ [-fpermissive] `#define P_PIDFD 3`

Hmmmm......... this is actually how Linux uapi headers define it

https://elixir.bootlin.com/linux/v5.12-rc3/source/include/uapi/linux/wait.h#L20

(why did the ifdef even fail… I've just added `linux/wait.h` include, anyway.)

What kernel and libc do you have? And which package provides files like `/usr/include/linux/wait.h`?

> error: ‘ptr_to_u64’ was not declared in this scope

I'm not sure where it's even supposed to come from tbh. Changed to a manual cast.

**Comment by botiapa** [comment]
I'm running lts-linux on arch. `uname-a`: `Linux 5.10.23-1-lts #1 SMP Thu, 11 Mar 2021 15:32:34 +0000 x86_64 GNU/Linux` I updated wayfire to the git version so it's now on: `0.7.0-2a1dacec (Mar 18 2021, branch 'master')`. Libc version: `ldd (GNU libc) 2.33` .

The older errors have disappeared fortunately, but another one arose: http://ix.io/2TkT I haven't had the time to look at the code yet, so unfortunately I have no idea what I might be doing wrong.

**Comment by unrelentingtech** [comment]
> lts-linux on arch

What an interesting combo, bleeding edge distro but lts kernel..

> error: invalid conversion from ‘int’ to ‘idtype_t’

That one's not new. Okay I'll add a cast I guess.

> error: designator order for field ‘clone_args::flags’ does not match declaration order in ‘clone_args’

This maybe sounds like gcc 10 stuff, that used to work. Whatever, changed to not use the initializer.

**Comment by botiapa** [comment]
Okay, thanks to the patches it now compiled fine, but I can't get it to actually display anything. I modified `wayfire.ini` so the plugins list includes `wallpaper` and I added a new section:

```
[wallpaper:w1]
path = /home/botond/Pictures/Wallpapers/backgroundCentered.png
workspaces = *
sizing_mode = fit
```

I can't find anything in the debug logs about wallpaper. The plugin should be installed though, the lib has been copied to /usr/local/lib/wayfire (by meson) Do I need to do something else too?

**Comment by unrelentingtech** [comment]
Did you modify the same config file that it's reading? (See `[src/default-config-backend.cpp:52] Using config file: …` in the log.)
You should at least get `[subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file …/share/wayfire/metadata/wallpaper.xml`

**Comment by botiapa** [comment]
Yes I modified the same file, however I noticed that it didn't read the `wallpaper.xml` file, so I copied it next to the other metadata files. So from `/usr/local/share/wayfire/metadata/wallpaper.xml` to `/usr/share/wayfire/metadata/wallpaper.xml` and I did the same with the .so library file. Now wayfire logs that it read the metadata file and loaded the plugin. Sadly, still no image output, however the plugin logged a whole bunch: http://ix.io/2Txf

**Comment by unrelentingtech** [comment]
well

> Could not fork, WTF?

The code before the recent initializer changes was tested by someone on linux before.
Changed a thing, maybe it'll work now.

> copied it next to the other metadata files

ninja install is supposed to do that

**Comment by botiapa** [comment]
Still getting the same error. (could not fork) I'd gladly run a debug version of the plugin or something, if it made it easier for you too locate the problem.

**Comment by unrelentingtech** [comment]
Just do something like `gcc -o pftest pid_fd_fork_test.c && strace ./pftest`

**Comment by ssfdust** [comment]
Hello,  here is the same platform archlinux but without lts kernel.

Here is output from strace
```
execve("./pftest", ["./pftest"], 0x7fffb14ba3b0 /* 78 vars */) = 0
brk(NULL)                               = 0x5585dbbc1000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffd49fc5ce0) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=195020, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 195020, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f4b7cef6000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`|\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0@\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 80, 848) = 80
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0T\246\344\4\347\334\35\347\301CJ\0\267\261\2552"..., 68, 928) = 68
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=2154488, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4b7cef4000
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1884632, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4b7cd27000
mmap(0x7f4b7cd4d000, 1359872, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f4b7cd4d000
mmap(0x7f4b7ce99000, 311296, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x172000) = 0x7f4b7ce99000
mmap(0x7f4b7cee5000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7f4b7cee5000
mmap(0x7f4b7ceeb000, 33240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f4b7ceeb000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4b7cd25000
arch_prctl(ARCH_SET_FS, 0x7f4b7cef5580) = 0
mprotect(0x7f4b7cee5000, 12288, PROT_READ) = 0
mprotect(0x5585da01b000, 4096, PROT_READ) = 0
mprotect(0x7f4b7cf55000, 8192, PROT_READ) = 0
munmap(0x7f4b7cef6000, 195020)          = 0
clone3(0x58, 88)                        = -1 EFAULT (Bad address)
brk(NULL)                               = 0x5585dbbc1000
brk(0x5585dbbe2000)                     = 0x5585dbbe2000
write(2, "pftest: pid_fd_fork_test.c:15: m"..., 65pftest: pid_fd_fork_test.c:15: main: Assertion `pid > 0' failed.
) = 65
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4b7cf54000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 2617873
gettid()                                = 2617873
tgkill(2617873, 2617873, SIGABRT)       = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=2617873, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
[1]    2617870 abort (core dumped)  strace ./pftest
```

**Comment by unrelentingtech** [comment]
> clone3(0x58, 88)

:D Should be fixed now

**Comment by ssfdust** [comment]
The plugin works, thank you!
