### ISSUE TITLE
Image loading issue after update

### ISSUE THREAD

**Issue by kbtz** [DankBSD/wf-wallpaper#4]
Recently images aren't being rendered anymore while shaders still work. Any clues?
  
<details><summary>Wayfire Log</summary>

```
EE 15-04-22 15:25:11.124 - [GLES2] GL_INVALID_OPERATION in glTexImage2D(immutable texture)
EE 15-04-22 15:25:11.124 - [src/core/opengl.cpp:42] gles2: function glTexImage2D(0x0DE1, 0, storage_fmt, hdr->width, hdr->height, 0, tex_fmt, 0x1401, (GLvoid *)(bytes + sizeof(shm_header))) in std::shared_ptr<std::variant<picture_t, shader_t> > load_renderable(shm_header*, size_t) line 183: UNKNOWN GL ERROR
II 15-04-22 15:25:11.124 - [wallpaper.cpp:289] Wallpaper loaded for /path/to/my-wallpaper.jpeg
```
</details>

**Comment by unrelentingtech** [comment]
Probably the result of #3… does reverting back to 3543946c6163822d4572ebf93f25ce332d70c000 help?

**Comment by kbtz** [comment]
Yep, it works again. I assume you tested #3 on desktop so perharps it might breaking only for intel graphics? Also, maybe the issue comes from the way image data is being passed because, as far I can see, all the other parameters to `glTexImage2D` are OK.
  
<details><summary>GL_INVALID_OPERATION@glTexImage2D</summary>

```
GL_INVALID_OPERATION is generated if the combination of internalFormat, format and type is not one of those in the tables above.

GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to the GL_PIXEL_UNPACK_BUFFER target and the buffer object's data store is currently mapped.

GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to the GL_PIXEL_UNPACK_BUFFER target and the data would be unpacked from the buffer object such that the memory reads required would exceed the data store size.

GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to the GL_PIXEL_UNPACK_BUFFER target and data is not evenly divisible into the number of bytes needed to store in memory a datum indicated by type.
```
</details>

**Comment by unrelentingtech** [comment]
Yes, I have only tested on RadeonSI.

Actually it seems that `glTexImage2D` *creates* storage, so now after #3 the `glTexStorage2D` call is wasted. Maybe Intel drivers (btw, are you on Iris or i965?) have a check that the storage isn't allocated already.

**Comment by kbtz** [comment]
@unrelentingtech That makes sense, thanks for the fix! That happened on i965.
